from pymycobot. mycobot import MyCobot
import time

mc = MyCobot ( 'COM6' , 115200)
mc.set_gripper_mode(0)
mc. init_eletric_gripper()
time.sleep(4)
while True:
    print("To ROOT Moving")
    mc. send_angles ( [0, 0, 0, 0, 0, 0],20)
    time.sleep(5)
    print("JOINT 1, 90degree Moving")
    mc.send_angle(1, 90, 20)
    time.sleep(4)
    print("JOINT 2, 60degree Moving")
    mc.send_angle(2, 60, 20)
    time.sleep(4)
    print("JOINT 4, -60degree Moving")
    mc.send_angle(4, (-60), 20)
    time.sleep(4)
    print("JOINT 5, -90degree Moving")
    mc.send_angle(5, (-90), 20)
    time.sleep(4)
    print("Gripper Close")
    mc.set_eletric_gripper(1)
    mc.set_gripper_value(100, 20)
    time.sleep(4)
    print("Gripper Open")
    mc.set_eletric_gripper(0)
    mc.set_gripper_value(0, 20)
    time.sleep(4)